name: CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install pnpm
        run: npm install -g pnpm@7.28.0

      - name: Install dependencies
        run: pnpm install

      - name: Check code style
        run: pnpm run lint
